//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities.Utilites.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities.Utilites.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SCV Конвертер.
        /// </summary>
        internal static string CSVConverter_ScreenName {
            get {
                return ResourceManager.GetString("CSVConverter_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string CsvDelimiter_Description {
            get {
                return ResourceManager.GetString("CsvDelimiter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделитель.
        /// </summary>
        internal static string CsvDelimiter_ScreenName {
            get {
                return ResourceManager.GetString("CsvDelimiter_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string EncodingType_Description {
            get {
                return ResourceManager.GetString("EncodingType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EncodingType.
        /// </summary>
        internal static string EncodingType_ScreenName {
            get {
                return ResourceManager.GetString("EncodingType_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входной файл данных в формате CSV..
        /// </summary>
        internal static string InputCsvFile_Description {
            get {
                return ResourceManager.GetString("InputCsvFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input.
        /// </summary>
        internal static string InputCsvFile_ScreenName {
            get {
                return ResourceManager.GetString("InputCsvFile_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Json в Словарь.
        /// </summary>
        internal static string JsonDictionary_ScreenName {
            get {
                return ResourceManager.GetString("JsonDictionary_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Out_Dict_Description {
            get {
                return ResourceManager.GetString("Out_Dict_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Словарь.
        /// </summary>
        internal static string Out_Dict_ScreenName {
            get {
                return ResourceManager.GetString("Out_Dict_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выходной файл для сохранения результата конвертации данных.
        /// </summary>
        internal static string OutputConvertedFile_Description {
            get {
                return ResourceManager.GetString("OutputConvertedFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output.
        /// </summary>
        internal static string OutputConvertedFile_ScreenName {
            get {
                return ResourceManager.GetString("OutputConvertedFile_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат, в который будет производиться конвертация (JSON, XML)..
        /// </summary>
        internal static string OutputFormat_Description {
            get {
                return ResourceManager.GetString("OutputFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат .
        /// </summary>
        internal static string OutputFormat_ScreenName {
            get {
                return ResourceManager.GetString("OutputFormat_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Patch_Description {
            get {
                return ResourceManager.GetString("Patch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к файлу JSON.
        /// </summary>
        internal static string Patch_ScreenName {
            get {
                return ResourceManager.GetString("Patch_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Success_Description {
            get {
                return ResourceManager.GetString("Success_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        internal static string Success_ScreenName {
            get {
                return ResourceManager.GetString("Success_ScreenName", resourceCulture);
            }
        }
    }
}
