//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SCV Конвертер.
        /// </summary>
        internal static string CSVConverter_ScreenName {
            get {
                return ResourceManager.GetString("CSVConverter_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Delimiter_Description {
            get {
                return ResourceManager.GetString("Delimiter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделитель.
        /// </summary>
        internal static string Delimiter_ScreenName {
            get {
                return ResourceManager.GetString("Delimiter_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Encoding_Description {
            get {
                return ResourceManager.GetString("Encoding_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encoding.
        /// </summary>
        internal static string Encoding_ScreenName {
            get {
                return ResourceManager.GetString("Encoding_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Excel_FileName_Description {
            get {
                return ResourceManager.GetString("Excel_FileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к файлу Excel.
        /// </summary>
        internal static string Excel_FileName_ScreenName {
            get {
                return ResourceManager.GetString("Excel_FileName_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ExcelReadRange_FirstRowIsHeader_Description {
            get {
                return ResourceManager.GetString("ExcelReadRange_FirstRowIsHeader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первая строка в Excel является заголовком.
        /// </summary>
        internal static string ExcelReadRange_FirstRowIsHeader_ScreenName {
            get {
                return ResourceManager.GetString("ExcelReadRange_FirstRowIsHeader_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ExcelReadRange_IgnoreEmptyRowsColumnsAtStart_Description {
            get {
                return ResourceManager.GetString("ExcelReadRange_IgnoreEmptyRowsColumnsAtStart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игнорировать пустые строки и столбцы в начале.
        /// </summary>
        internal static string ExcelReadRange_IgnoreEmptyRowsColumnsAtStart_ScreenName {
            get {
                return ResourceManager.GetString("ExcelReadRange_IgnoreEmptyRowsColumnsAtStart_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ExcelReadRange_Range_Description {
            get {
                return ResourceManager.GetString("ExcelReadRange_Range_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диапазон для чтения данных из Excel.
        /// </summary>
        internal static string ExcelReadRange_Range_ScreenName {
            get {
                return ResourceManager.GetString("ExcelReadRange_Range_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входной файл.
        /// </summary>
        internal static string InputFile_Description {
            get {
                return ResourceManager.GetString("InputFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input.
        /// </summary>
        internal static string InputFile_ScreenName {
            get {
                return ResourceManager.GetString("InputFile_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string InputFormat_Description {
            get {
                return ResourceManager.GetString("InputFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InputFormat.
        /// </summary>
        internal static string InputFormat_ScreenName {
            get {
                return ResourceManager.GetString("InputFormat_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Json в Словарь.
        /// </summary>
        internal static string JsonDictionary_ScreenName {
            get {
                return ResourceManager.GetString("JsonDictionary_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Out_Dict_Description {
            get {
                return ResourceManager.GetString("Out_Dict_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Словарь.
        /// </summary>
        internal static string Out_Dict_ScreenName {
            get {
                return ResourceManager.GetString("Out_Dict_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выходной файл для сохранения результата конвертации данных.
        /// </summary>
        internal static string OutputConvertedFile_Description {
            get {
                return ResourceManager.GetString("OutputConvertedFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output.
        /// </summary>
        internal static string OutputConvertedFile_ScreenName {
            get {
                return ResourceManager.GetString("OutputConvertedFile_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string OutputFile_Description {
            get {
                return ResourceManager.GetString("OutputFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OutputFile.
        /// </summary>
        internal static string OutputFile_ScreenName {
            get {
                return ResourceManager.GetString("OutputFile_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат, в который будет производиться конвертация (JSON, XML)..
        /// </summary>
        internal static string OutputFormat_Description {
            get {
                return ResourceManager.GetString("OutputFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат .
        /// </summary>
        internal static string OutputFormat_ScreenName {
            get {
                return ResourceManager.GetString("OutputFormat_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Patch_Description {
            get {
                return ResourceManager.GetString("Patch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к файлу JSON.
        /// </summary>
        internal static string Patch_ScreenName {
            get {
                return ResourceManager.GetString("Patch_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string SettingFile_DataResult_Description {
            get {
                return ResourceManager.GetString("SettingFile_DataResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат выполнения.
        /// </summary>
        internal static string SettingFile_DataResult_ScreenName {
            get {
                return ResourceManager.GetString("SettingFile_DataResult_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string SettingFile_Mode_Description {
            get {
                return ResourceManager.GetString("SettingFile_Mode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим выполнения алгоритма.
        /// </summary>
        internal static string SettingFile_Mode_ScreenName {
            get {
                return ResourceManager.GetString("SettingFile_Mode_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excel в Словарь.
        /// </summary>
        internal static string SettingFileCombined_ScreenName {
            get {
                return ResourceManager.GetString("SettingFileCombined_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Success_Description {
            get {
                return ResourceManager.GetString("Success_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        internal static string Success_ScreenName {
            get {
                return ResourceManager.GetString("Success_ScreenName", resourceCulture);
            }
        }
    }
}
